---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - policies/dev/policy-generator-config.yaml
  - policies/prod/policy-generator-config.yaml
resources:
  - policies/dev/placement.yml
  - policies/prod/placement.yml
