---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - policy-generator-dev.yaml
  - policy-generator-prod.yaml
resources:
  - policies/dev/placement.yml
  - policies/prod/placement.yml
