---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-certmanager-dev
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
  consolidateManifests: false
  severity: medium
  placement:
    placementName: cert-manager-dev-placement
  categories:
    - "CM Configuration Management"
  controls:
    - "CM-2 Baseline Configuration"
  standards:
    - "NIST SP 800-53"

policies:
  - name: dev-cert-manager-clusterissuer
    description: "Deploys dev CA based ClusterIssuer"
    dependencies:
      - name: cert-manager-operator
        compliance: Compliant
    manifests:
      - path: ca-clusterissuer.yml
        name: ca-clusterissuer-dev
        extraDependencies:
          - name: ca-clusterissuer-secret
            kind: ConfigurationPolicy
            compliance: "Compliant"
