---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: cert-manager-prod-placement
  namespace: acm-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            environment: prod
