---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-certmanager-dev
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
  consolidateManifests: false
  severity: medium
  placement:
    placementName: cert-manager-dev-placement
  categories:
    - "CM Configuration Management"
  controls:
    - "CM-2 Baseline Configuration"
  standards:
    - "NIST SP 800-53"

policies:
  - name: dev-cert-manager-operator
    description: "Installs cert-manager operator on dev clusters"
    manifests:
      - path: ../../manifests/base/namespace.yml
        name: cert-manager-operator-namespace

      - path: ../../manifests/base/trusted-ca-configmap.yml
        name: trusted-ca-configmap

      - path: ../../manifests/base/operatorpolicy.yml
        name: cert-manager-operator-install

      - path: ../../manifests/health/cert-manager-status.yml
        name: cert-manager-status
        remediationAction: InformOnly

      - path: ../../manifests/base/cert-manager-namespace.yml
        name: cert-manager-namespace

      - path: ../../manifests/base/ca-clusterissuer-secret.yml
        name: ca-clusterissuer-secret

  - name: dev-cert-manager-clusterissuer
    description: "Deploys dev CA based ClusterIssuer"
    dependencies:
      - name: dev-cert-manager-operator
        compliance: Compliant
    manifests:
      - path: ca-clusterissuer.yml
        name: ca-clusterissuer-dev
        extraDependencies:
          - name: ca-clusterissuer-secret
            kind: ConfigurationPolicy
            compliance: "Compliant"
